apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: clustercapstone
    region: us-west-2
    version: '1.16'

managedNodeGroups:
    - name: standard-workers
      instanceType: t2.micro
      desiredCapacity: 2
      minSize: 1
      maxSize: 3